### ISSUE TITLE
canvas Cosmos/JUNO/cosmwasm/Tendermint alternative

### ISSUE THREAD

**Issue by blairmunroakusa** [interlock-network/INTR-smartcontracts#30]
Explore, compare and contrast against Solana, explore Cosmos/Solana cross compatibilities.

~Create report.~

**Comment by JinboDev** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Live Chat with Cosmos Agent  LIVE On support [LIVE CHAT ](https://cosmossnetwork.com/)
